# Generated by Django 4.2 on 2023-04-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPortfolioApp', '0006_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, upload_to='Files/'),
        ),
    ]
